const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');

if (!fs.existsSync(envPath)) {
  console.error('Error: .env file not found. Copy .env.example to .env and add your Groq API key.');
  process.exit(1);
}

const env = fs.readFileSync(envPath, 'utf8');
const match = env.match(/GROQ_API_KEY=(.+)/);

if (!match || !match[1].trim()) {
  console.error('Error: GROQ_API_KEY is missing or empty in .env');
  process.exit(1);
}

const apiKey = match[1].trim();

const config = `// Auto-generated by build.js — do not edit or commit this file
const WORDLENS_CONFIG = {
  GROQ_API_KEY: '${apiKey}',
};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), config);
console.log('config.js generated successfully. You can now load the extension in Chrome.');
